---
- hosts: localhost
  become: false
  gather_facts: no

  tasks:
  - name: ensure git is at the latest version
    apt:
      name: git
      state: latest

  - name: clone the repo
    shell: git clone https://github.com/Hunter-Thompson/helloworld-node.git
  
  - name: build the docker image 
    shell: cd helloworld-node && docker build -t helloworld .
  
  - name: push docker image 
    shell: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $IAM_ID-us-east-1.amazonaws.com/helloworld:latest && docker tag helloworld:latest $IAM_ID.dkr.ecr.us-east-1.amazonaws.com/helloworld:latest && docker push $IAM_ID.dkr.ecr.us-east-1.amazonaws.com/helloworld:latest

  - name: apply kubernetes file
    shell: kubectl apply -f helloworld.yml

